export const PLACE_MARKER_ICON = {
  CANVAS_CLEAR_RECT_X: 0,
  CANVAS_CLEAR_RECT_Y: 0,
  FILL_COLOR_DEFAULT: '#969696',
  FILL_COLOR_SELECTED: '#09DDDF',
  STROKE_COLOR: '#FFFFFF',
  LINE_WIDTH: 7,
  SHADOW_BLUR: 1,
  ARC_START_ANGLE: 0,
};

export const MARKER_SIZE = 35;