export const D3_INTERESTS_DATA = {
  BUBBLE_RADIUS_DELTA: 0.4,
  LARGE_BUBBLE_SIZE: 40,
  MEDIUM_BUBBLE_SIZE: 35,
  SMALL_BUBBLE_SIZE: 25
};

export const EFFECTS_PARTICLE = {
  MIN_RADIUS: 1,
  MAX_RADIUS: 50,
  FILL_COLOR: 'transparent',
  STROKE_WIDTH: 5,
  STROKE_COLOR: '#09DDDF',
  STROKE_START_OPACITY: 1,
  STROKE_STOP_OPACITY: 1e-6,
  TRANSITION_DURATION: 500
};

export const EFFECTS_SIMULATION_TO_CENTER = {
  VELOCITY_DECOY: 0.1,
  FORCE_STRENGTH_X: 0.01,
  FORCE_STRENGTH_Y: 0.01,
  COLLIDE_RADIUS_DELTA: 0.5,
  COLLIDE_ITERATIONS: 3,
  FILL_CIRCLE_TRANSITION: '1s',
  FILL_TEXT_START_COLOR: '#09DDDF',
  FILL_TEXT_STOP_COLOR: '#FFFFFF',
  FILL_CIRCLE_START_COLOR: '#09DDDF',
  FILL_CIRCLE_STOP_COLOR: 'transparent',
  FONT_SIZE_DELTA: 5
};

export const SVG_CIRCLE = {
  STROKE_COLOR: '#09DDDF',
  STROKE_WIDTH: 2,
  FILL_COLOR: '#FFFFFF'
};

export const SVG_TEXT = {
  FILL_COLOR: '#09DDDF'
};